export CONFIG_PINCTRL_LPI=n
export CONFIG_PINCTRL_WCD=n
export CONFIG_AUDIO_EXT_CLK=n
export CONFIG_SND_SOC_WCD9XXX_V2=n
export CONFIG_SND_SOC_WCD_MBHC=n
export CONFIG_WCD9XXX_CODEC_CORE_V2=n
export CONFIG_MSM_CDC_PINCTRL=n
export CONFIG_MSM_QDSP6V2_CODECS=n
export CONFIG_MSM_QDSP6_APRV2_RPMSG=n
export CONFIG_MSM_ADSP_LOADER=n
export CONFIG_REGMAP_SWR=n
export CONFIG_MSM_QDSP6_SSR=n
export CONFIG_MSM_QDSP6_PDR=n
export CONFIG_MSM_QDSP6_NOTIFIER=n
export CONFIG_SND_SOC_MSM_HOSTLESS_PCM=n
export CONFIG_SND_SOC_MSM_QDSP6V2_INTF=n
export CONFIG_SOUNDWIRE=n
export CONFIG_SOUNDWIRE_MSTR_CTRL=n
export CONFIG_SND_SOC_QDSP6V2=n
export CONFIG_SND_SOC_WCD_MBHC_ADC=n
export CONFIG_SND_SOC_MSM_HDMI_CODEC_RX=n
export CONFIG_QTI_PP=n
export CONFIG_SND_HWDEP_ROUTING=n
export CONFIG_SND_SOC_MSM_STUB=n
export CONFIG_SND_SOC_BOLERO=n
export CONFIG_WSA_MACRO=n
export CONFIG_VA_MACRO=n
export CONFIG_RX_MACRO=n
export CONFIG_TX_MACRO=n
export CONFIG_SND_SOC_WCD_IRQ=n
export CONFIG_SND_SOC_WCD938X=n
export CONFIG_SND_SOC_WCD938X_SLAVE=n
export CONFIG_SND_SOC_WCD937X=n
export CONFIG_SND_SOC_WCD937X_SLAVE=n
export CONFIG_SND_SOC_WSA883X=n
export CONFIG_SND_SOC_SWR_DMIC=n
export CONFIG_SND_SOC_LAHAINA=n
export CONFIG_SND_EVENT=n
export CONFIG_SND_SWR_HAPTICS=n
export CONFIG_DIGITAL_CDC_RSC_MGR=n
export CONFIG_AUXPCM_DISABLE=n
